title: P-SSCRM Documentation
email: pjmorris@ncsu.edu
description: The Proactive Software Supply Chain Risk Management Framework (P SSCRM) described here  is designed to help you understand and plan a secure software supply chain risk management initiative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  p-sscrm

# Build settings
theme: minima
#remote_theme: pages-themes/merlot@v0.2.0
#remote_theme: pages-themes/modernist@v0.2.0
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-remote-theme

# Collections for framework components
collections:
  groups:
    output: true
    permalink: /framework/groups/:name/
  practices:
    output: true
    permalink: /framework/practices/:name/
  tasks:
    output: true
    permalink: /framework/tasks/:name/
  frameworks:
    output: true
    permalink: /framework/frameworks/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "groups"
    values:
      layout: "group"
  - scope:
      path: ""
      type: "practices"
    values:
      layout: "practice"
  - scope:
      path: ""
      type: "tasks"
    values:
      layout: "task"
  - scope:
      path: ""
      type: "frameworks"
    values:
      layout: "framework"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor
   - spec
   - README.md
   - Rakefile
   - .git
